name: Lint and Format Check

description: >
  Runs HTML, CSS, and JavaScript linters to ensure code quality and consistency.

on:
  push:
    branches: [main, fresh-start]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run HTML Linter
        run: npm run lint:html

      - name: Run CSS Linter
        run: npm run lint:css

      - name: Run JavaScript Linter
        run: npm run lint:js

      - name: Check Code Formatting
        run: npm run format:check

      - name: Run Full Validation
        run: npm run validate

  lint-fix:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Auto-fix Linting Issues
        run: npm run lint:fix

      - name: Format Code
        run: npm run format

      - name: Create Pull Request with Fixes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: auto-fix linting and formatting issues'
          title: '🔧 Auto-fix linting and formatting issues'
          body: |
            This PR automatically fixes linting and formatting issues found by our linters.
            
            ## Changes Made:
            - Fixed HTML validation issues
            - Corrected CSS formatting and best practices
            - Improved JavaScript code quality
            - Applied consistent code formatting
            
            ## Linters Used:
            - HTMLHint for HTML validation
            - Stylelint for CSS best practices
            - ESLint for JavaScript quality
            - Prettier for consistent formatting
          
          branch: auto-fix/linting-issues
          delete-branch: true 